export const meatDishes = [
    { id: 1, name: 'Keftedes', description: "grekiska köttbullar", rating: 4.5, ingredients: ['Köttfärs', 'Lök', 'Vittlök', 'Ägg', 'Pepper', 'Origano']},
    { id: 2, name: 'Mousaka', description: "Traditional plate", rating: 3.6, ingredients: ['Köttfärs', 'Lök', 'Potatis', 'Grädde', 'Aubergin']},
    { id: 3, name: 'Paidakia med potatiss', description: "Lamkops", rating: 4.7, ingredients: ['Lampkops', 'Lök', 'Potatis', 'Olja', 'Pepper']},
    { id: 4, name: 'Kleftiko', description: "Lamkött", rating: 4.8, ingredients: ['Lamp', 'Freshlök', 'Tomatsås', 'Olja']},
    { id: 5, name: 'Pasta me kima', description: "Pasta", rating: 3.2, ingredients: ['Pasta', 'Köttfärs', 'Ost', 'OLja', 'Vittlök']},
    { id: 6, name: 'Pita guro', description: "Pita med kött", rating: 4, ingredients: ['Kött', 'Pita', 'Tzatziki', 'Potatis', 'Lök']},
    { id: 7, name: 'Xwriatiki salata', description: "Salad", rating: 4.5, ingredients: ['Fetaost', 'Tomat', 'Freshlök', 'Gurka', 'Olivolja', 'Kapari']},
    { id: 8, name: 'Giouvetsi', description: "Kött", rating: 4.6, ingredients: ['Beef', 'Smålök', 'Tomatsås', 'Potatis']},
    { id: 9, name: 'Pastitsio', description: "Pasta", rating: 3.4, ingredients: ['Pasta', 'Grädde', 'Köttfärs', 'Tomasås', 'Ost']},
    { id: 10, name: 'Prasoselino', description: "Purjölök", rating: 3.7, ingredients: ['Purjölock', 'Fläskkött', 'Lök',]},
    { id: 11, name: 'Korv Stroganoff', description: "Korv", rating: 4.9, ingredients: ['Korv', 'Lök', 'Tomatpuré', 'Grädde'] },
    { id: 12, name: 'Biff Stroganoff', description: "Biff", rating: 4.6, ingredients: ['Biff', 'Lök', 'Svamp', 'Grädde'] },
    { id: 13, name: 'Köttbullar', description: "Kött", rating: 4.9, ingredients: ['Köttfärs', 'Lök', 'Ströbröd', 'Mjölk', 'Ägg'] },
    { id: 14, name: 'Kalops', description: "Kött", rating: 4.2, ingredients: ['Nötkött', 'Morötter', 'Lök', 'Kryddpeppar'] },
    { id: 15, name: 'Pannbiff', description: "Biffkött", rating: 4.9, ingredients: ['Nötkött', 'Lök', 'Ströbröd', 'Ägg'] },
    { id: 16, name: 'Fläskfilégryta', description: "Fläskkött", rating: 3.8, ingredients: ['Fläskfilé', 'Grädde', 'Lök', 'Champinjoner'] },
    { id: 17, name: 'Kycklinggryta', description: "Kyckling", rating: 4.2, ingredients: ['Kyckling', 'Lök', 'Paprika', 'Tomater'] },
    { id: 18, name: 'Stekt lax', description: "Fisk", rating: 4.3, ingredients: ['Lax', 'Citron', 'Dill', 'Smör'] },
    { id: 19, name: 'Kåldolmar', description: "Vegetaris", rating: 4.1, ingredients: ['Kål', 'Nötkött', 'Ris', 'Lök'] },
    { id: 20, name: 'Sjömansbiff', description: "Biffkött", rating: 4.6, ingredients: ['Nötkött', 'Potatis', 'Lök', 'Öl'] },
];
