export const meatDishes = [
    { id: 1, name: 'Keftedes', ingredients: ['Köttfärs', 'Lök', 'Vittlök', 'Ägg', 'Pepper', 'Origano']},
    { id: 2, name: 'Mousaka', ingredients: ['Köttfärs', 'Lök', 'Potatis', 'Grädde', 'Aubergin']},
    { id: 3, name: 'Paidakia med potatiss', ingredients: ['Lampkops', 'Lök', 'Potatis', 'Olja', 'Pepper']},
    { id: 4, name: 'Kleftiko', ingredients: ['Lamp', 'Freshlök', 'Tomatsås', 'Olja']},
    { id: 5, name: 'Pasta me kima', ingredients: ['Pasta', 'Köttfärs', 'Ost', 'OLja', 'Vittlök']},
    { id: 6, name: 'Pita guro', ingredients: ['Kött', 'Pita', 'Tzatziki', 'Potatis', 'Lök']},
    { id: 7, name: 'Xwriatiki salata', ingredients: ['Fetaost', 'Tomat', 'Freshlök', 'Gurka', 'Olivolja', 'Kapari']},
    { id: 8, name: 'Giouvetsi', ingredients: ['Beef', 'Smålök', 'Tomatsås', 'Potatis']},
    { id: 9, name: 'Pastitsio', ingredients: ['Pasta', 'Grädde', 'Köttfärs', 'Tomasås', 'Ost']},
    { id: 10, name: 'Prasoselino', ingredients: ['Purjölock', 'Fläskkött', 'Lök',]},
    { id: 11, name: 'Korv Stroganoff', ingredients: ['Korv', 'Lök', 'Tomatpuré', 'Grädde'] },
    { id: 12, name: 'Biff Stroganoff', ingredients: ['Biff', 'Lök', 'Svamp', 'Grädde'] },
    { id: 13, name: 'Köttbullar', ingredients: ['Köttfärs', 'Lök', 'Ströbröd', 'Mjölk', 'Ägg'] },
    { id: 14, name: 'Kalops', ingredients: ['Nötkött', 'Morötter', 'Lök', 'Kryddpeppar'] },
    { id: 15, name: 'Pannbiff', ingredients: ['Nötkött', 'Lök', 'Ströbröd', 'Ägg'] },
    { id: 16, name: 'Fläskfilégryta', ingredients: ['Fläskfilé', 'Grädde', 'Lök', 'Champinjoner'] },
    { id: 17, name: 'Kycklinggryta', ingredients: ['Kyckling', 'Lök', 'Paprika', 'Tomater'] },
    { id: 18, name: 'Stekt lax', ingredients: ['Lax', 'Citron', 'Dill', 'Smör'] },
    { id: 19, name: 'Kåldolmar', ingredients: ['Kål', 'Nötkött', 'Ris', 'Lök'] },
    { id: 20, name: 'Sjömansbiff', ingredients: ['Nötkött', 'Potatis', 'Lök', 'Öl'] },
];
